### ISSUE TITLE
How can I use a concrete class for certain constructor parameters?

### ISSUE THREAD

**Issue by flipdoubt** [michal-ciechan/Moqqer#11]
I have the following constructor `public ConfigureCatalogHandler(IFileSystem fileSystem, ILogger logger)` where I want to pass in an actual logger implementation so I see progress output to the test console. Am I missing a way to accomplish this? I keep looking for something like `Moq.Of<ILogger>().Use(new TestLogger())`. Any way to get this done using the current implementation? If not, can you suggest a work around?

**Comment by michal-ciechan** [comment]
Hey David,

This is definitely something I will add! (hopefully next week as I'm away till Monday). until now I have been verifying the expected Mock methods are called, e.g. Moq.Verify<ILogger>(x => x.LogInfo("Some Message")).Once().

But I can definitely see the benefit of aging a Use(implementation) method so will add it next week!

Thanks the feedback!

Get Outlook for Androidhttps://aka.ms/ghei36

From: David Smith
Sent: Saturday, 8 October, 18:20
Subject: [michal-ciechan/Moqqer] How can I use a concrete class for certain constructor parameters? (#11)
To: michal-ciechan/Moqqer

I have the following constructor public ConfigureCatalogHandler(IFileSystem fileSystem, ILogger logger) where I want to pass in an actual logger implementation so I see progress output to the test console. Am I missing a way to accomplish this? I keep looking for something like Moq.Of<ILogger>().Use(new TestLogger()). Any way to get this done using the current implementation? If not, can you suggest a work around?

##

**Comment by flipdoubt** [comment]
Also useful for non-mockable objects and primitives that should be a certain value to produce a certain result.

**Comment by michal-ciechan** [comment]
Hey David, 

Checkout https://github.com/michal-ciechan/Moqqer#concrete-implementation

`_moq.Use<IFizz>(fizz);`

So you should be able to do o:

Moq.Use<Ilogger>(new TestLogger());

**Comment by flipdoubt** [comment]
Looks like the usage I would expect, but it does not appear to be available
via Nuget.

**Comment by michal-ciechan** [comment]
Yes, just fixing my TC build. Will update once NuGet package is available + indexed

**Comment by flipdoubt** [comment]
Awesome!

**Comment by michal-ciechan** [comment]
Should be available now on NuGet
