### ISSUE TITLE
.NET Standard

### ISSUE THREAD

**Issue by michal-ciechan** [michal-ciechan/Moqqer#36]

**Comment by damianpumar** [comment]
Hello @michal-ciechan do you need help to migrate net standard?

Cheers!

**Comment by michal-ciechan** [comment]
Hey @damianpumar, sorry for the late reply, but yes I have been meaning to do it, as my .net core test projects are complaining, but I haven't looked into it yet! I definitely help migrating it to .net standard if you know how or are have some spare time to look into it!

**Comment by damianpumar** [comment]
Perfect!, I'm in, I have some spare time to begin migration.
do you create new branch for this?

Regards!

**Comment by michal-ciechan** [comment]
I just created a develop branch. which I guess you can fork, and then work + PR to. let me know if you need any help or have any questions!

**Comment by damianpumar** [comment]
Perfect, if I have any question I'll write here!

Regards!

**Comment by damianpumar** [comment]
@michal-ciechan do you want I create slack channel for communicate faster?

Regards!

**Comment by michal-ciechan** [comment]
@damianpumar Hey, Slack is blocked at my work place, can we use gitter? [gitter.im/moqqer-project](gitter.im/moqqer-project
)

**Comment by damianpumar** [comment]
Perfect, yes I can.

**Comment by michal-ciechan** [comment]
I have migrated this to the new .csproj format and set TargetFrameworks to

```xml
<TargetFrameworks>net45;netstandard20</TargetFrameworks>
```

in line with current version of Moq. Therefore closing this specific issue.

I have created Issue #39 to track migrating to DryIoc

**Comment by damianpumar** [comment]
Ok, perfect, but, do you still working on this project?
Thanks!

**Comment by michal-ciechan** [comment]
Yes, not super actively, but I and a few others use it at work almost every day, or at least whenever we do an testing/TDD. We recently slowly starting doing .NET Core, and this was causing warnings as it was only targeting .NET Framework.

**Comment by damianpumar** [comment]
Haa, ok, cause I wrote to you few months ago from Gitter and I didn't received any message.
